---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: database
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgDVlE6hYhnvgAJBzmvv9Kva7Hwcp18Z0dqKQZaVScYc3BwQ788jnapyxIq8xJvUPNJ21R7j/CN53ZNWdX/l5N/x/u3jEGPnKJc/Mkgnxh40UY9XB9QzNyTPSgKgeDYEjMHeXVqQ3Um3ul/KuAHRs/BSGa8VPjrfKgkdmrPwZkC2rwjcBPkXRo/cnGu7uOgfEFLIJPb0NxjMgMAtQo+9AH2SYK1OUpmfB8gUCj7LdnB4euT6Wl5HBwYcpEakPUjwuS/NQfsReEy/zPl5TXz1Qv477vdOGIK2yCOJSMnQx3FrTdNDzFA4bMAF7b7lsPmBiWkncJezWEptN+kvJGoyNhXcBs5f+d2oneyi/uCevq7Sjoc+khjuOn37lpVqokdUC+PepeUknoVe4Z1TQ1Dkf/T1kaGrDC+0ZYoVmskFEto2/4TgP0tfaZvNNjpfqveyLvVoaSoJMsq4HDKMlKo9gVSLir3MgF9D9SknfFnAdlCApPUUUIjMtYpK4WcElZ5kSQga5etCvww4UUZ7wQPju3blIkYZLp+TgBAKciM6a0a7sDScy/4FgF7c5lT4RA7R2wtDq+SDFyWboxTlJYHjpfP8CrRtPhzP9UlmTQdwwtSCYU4ydAxjons2L8RGwjOJoxAbiSDRkoGjO2jZrFplAN13iAW1vv6yhrQAzUDM2Oa+fhP7FASpOCRdPLXbBVL8T7c4ojoDQIW3
  template:
    metadata:
      name: mysql-credentials
      namespace: database
