---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: database
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBIOkQ4jprgAeq2riTeeMxcsY/0HlvrpbmcAa2CTQbIZVvUWDGKd4rTncWg88WgIjZAhQ3Aiy3wJLuYEwbRXl7Oejaz69l5hJKv6I5EoE4ww/zdr3gG7d0LVJfXI4ZGrc4rZHBaGl3CP7Tf5jNWYNy5O5WsuWW2LIn2+4olQc+xLGfpdOhcKQ4DCgO2f21cO3C0rHI1U6pUjN+C5qk9vZC/H1mYQ7JgXnQXouuPsnWlFEz8jb66dbnxEzMeUKOT/cHxY6GxNlDdIB+2iUetdAv8oWvs2gDeCtjOtw5e91yJWfNtAHByKcoLqX3/e5cqycbnXM/D2I37NsKFAEaV2OPDzn3039TsAYXmgsETdTEGmkyoVfa5Y0VjPrykP/4MZ32OnkDPTtIQu89QybVYaBQDs8/0e8RF6V0ri9Q3GquKeKGj/F3+1ub+TvZlrOhX4z603DE5BS8KUvoz/boOv2JDxUlkhCfzZtjfpJ6CWOMWYYE56c4vQ23gkvlkKlFo7Wgw5lm5CEVbK2Gp3u8LzFCuo6zGk1EYSbgYcMYns9Tl9t5fmJKXMv7SIXEx0J4eXydlMF4Ub3SHfj0JemXXXNegc/7M0U4K3PNEzO39N5hdj4uRKB1+Y5qlD+MJV1SOxszF9UXN5mDFG+YZnNIthgTNNP1kHlOUvvDxcZbOr4w1k4puf59q+nAJnHtfOhjRLVpDGbpXfMyK
  template:
    metadata:
      name: mysql-credentials
      namespace: database
