---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: database
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAG0ZrM8fGvqymv3Xq4ijvrBwp0yy8Y1XSPG9ksZhcWB06Wr9xCJt2jE+iPKVDigpX9rvR6zaxHs9wxWPx4lY+J7Ec7qqepnStqbw1iyW9t7nqWQDT0VlDw/d3yuDtBPweQLRfBg6Xtkdu9OFzuxYd6gIddCd8qhLGRUIfSK5xGjghRb4r/Rz1i9XQ/HwsILandPomtHRLPG8ewP1ueq8m1pFuCtYOOPC6ZgsW7zOP/OHopN7F+tpkCpuvJNTJCxxnQLCiRjliFOLYmBk/W3tL9ZRf6tXdOIpsR+tkyaM3mOk4GC1QQYq/OOC4mopsC6ZVID0BbsbslfPjDQ61Qgu18o24EM+jdvx5wv7B6dErHO6AVis99NBRlDAJ9OPHPiQyoA6kG2X+D54N8Xf5cpi5E5LLYfkLdzsZ2rrRevLTcQNPntYHNYbNgKWiHhbFlPEaxYoPC1MeJFhi2Bp80qM7cwyph3IfyDO85rF8n/XuYPK5OVJrDyamUhlfA0K7PSQi3928TKnZSsUgxsVWdteP68bHpJUatn7Q1JwGN6q1hnWUsPBBJq7CHnzSnYnS33O2dBBDYymlb68c9D+cb0hErgnybZVFcYryQ0D8orXcecGgnHuW3B7D1k7M5juIWgmDr3DnTX4KhqnulqeKgMD4NXlC30NG1OddLmdJ5v9SMIYltrLdGlnzUJjEuKNK25xS5M6zMWMy1
  template:
    metadata:
      name: mysql-credentials
      namespace: database
