---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-credentials
  namespace: database
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBCKmwNfUY5DiWCy4TWVGQOULQxLqt4EFnkBiW7MZPY25Z4JpLnzocINCzUYvOD7Z/TmP3teUTr5zsyL79ZW7YVK7KkHUCRIVGAyBt1EZUuKdZvVIKyLH5vLwPRs0jTdkCDv2DgbiQ/XfPdOxe+QHey6C6m5UP0vxVtKkLyLxfZAXvB0QdPJVfE6VuLITykuEtmjB2RQoP16QFWbhN+qQ8sUFFaSI251F13AmX0clfYnLTGEAUbVsqN4Db9tIizsFegzMwTwN9xBnfoXzQXYWmL8w7k4JhOzrd/NSMy9Hl9ycLlKuchlXpAE8Vk0sWYA+0F+ajxdj4bJUdh73PgF8yOw2DRkbgf+DKjRqztIyaU6PGkygYHTNngyZtGWoo00jU8lqHdhBzMp0cQ3dxSCRW0b664jvXqALCdhjhTsuhSWRKesdVXM8v0IJ1thNu195lMQZrk9ic7HpS/0if3eMoNPSTfeQSeg8kWk92lGDE14bUmtRufoPWF/FPPrQY8esq1pBMnxDEZ+LhKS8uONQvkYOlnaaqqQELjjssWU/U9Gq++B9mUAfOzLHcwj37D0W8nZtJbpnY6TLhbM6LlHyav1pjO52C7QW7fSQagsJ+ofcL6pgFt0G9Pb9Kjk0vMRYCaHajp03AhtTQmCxNQaOlMMwPy8ciyFYsMJ33VE0K2gOFVw9kU8zzkb5P5SIUxmFCSPpxZNPI6
  template:
    metadata:
      name: mysql-credentials
      namespace: database
